### ISSUE TITLE
Preview icon is not available when choosing 'Start printing after upload' in PrusaSlicer

### ISSUE THREAD

**Issue by tychop** [jneilliii/OctoPrint-PrusaSlicerThumbnails#13]
Tiny bug I think:
The preview icon is not available when choosing 'Start printing after upload' in PrusaSlicer.
It only shows up when you do not print it immediately, or when the print is finished.

For the rest, 👍🏻💪🏻
Great job.

**Comment by jneilliii** [comment]
Not really a bug, it was actually programmed that way. The image itself is extracted during the upload process, but because file analysis doesn't start/ complete before the print starts the url doesn't get added to the metadata until after print completion. This was a limitation in the core octoprint plugin framework because none of the metadata exists until after that file analysis is completed. It's the same reason why the little arrow drop down doesn't become enabled until after print completion with auto start print as well. 

I will verify this with the plugin framework just to be sure.

**Comment by tychop** [comment]
Ah, yes. That explains a lot. Nowhere to hook into to run your code... Thnx

**Comment by bbrendon** [comment]
Ahhh... Can this be added to the readme? I think a lot of people are going to wonder about this.

**Comment by jneilliii** [comment]
That is probably a good idea @bbrendon, but I was hoping to be able to program around it, just haven't had the time to look into it yet.

**Comment by jneilliii** [comment]
Updated this repositories readme with a note that I'm working on it for the next release.

**Comment by jneilliii** [comment]
New version released that resolved this issue.

**Comment by tychop** [comment]
Works !!!
Thnx
