### ISSUE TITLE
Touch UI Interface Icons

### ISSUE THREAD

**Issue by TheNore** [jneilliii/OctoPrint-PrusaSlicerThumbnails#27]
After trying to manipulate the different view options i am unable to get the files to print from my touch UI instance. Only the website works. which is very inconvenient, and breaks my workflow.

This is a very important feature and it renders the use of touch ui semi useless as a standalone controller.

Images below reflect inline and stateless views. Paul de Vries (BillyBlaze) Might have to alter Touch UI to work with this plugin. 
![IMG_20200428_101320](https://user-images.githubusercontent.com/16988567/80499422-f59c6f80-893a-11ea-8fc4-95df5fd1989a.jpg)

![IMG_20200428_090033](https://user-images.githubusercontent.com/16988567/80499517-1795f200-893b-11ea-9845-a0577b5c0d16.jpg)

**Comment by jneilliii** [comment]
It looks like you also have the gcode editor plugin installed? I personally don't use TouchUI in preference of OctoDash, but have made changes to other plugins to get around TouchUI issues by disabling it completely if TouchUI is running and enabled.

**Comment by jneilliii** [comment]
And maybe you should also cross-post an issue on TouchUI's repository so @BillyBlaze actually sees it.

**Comment by jneilliii** [comment]
I cannot re-create this issue with gcode editor and touchui and this plugin all installed at the same time. So I think this was either fixed by those other plugins, are some of the changes in my current 0.1.5rc6 version has fixed this. Closing for now, please comment if this is still an issue for you with 0.1.5rc6 version of the plugin.
