### ISSUE TITLE
Plugin with Themeifiy

### ISSUE THREAD

**Issue by flc85** [jneilliii/OctoPrint-PrusaSlicerThumbnails#6]
Hello,
Sorry I don't understand what I must to do in Themeify with this line: 
`div.row-fluid.inline_prusa_thumbnail > img`
Can you explain me?

**Comment by jneilliii** [comment]
So the sizing option was added to the plugin's settings, so that is kind of an old reference that I need to probably remove. What I meant to say is that the file list itself may need to be resized to show more items in the list when the inline image option is enabled. For that you would enter the following configuration in themeify.

| Selector                                            | CSS_Rule   | Value            |
|-----------------------------------------------------|------------|------------------|
| #files > div > div.gcode_files > div.scroll-wrapper | min-height | 800px !important |

**Comment by thisiskeithb** [comment]
In addition to adding the custom CSS mentioned above under the Themify plugin & modifying my PrusaSlicer configs, I didn't realize I had to enable "Use inline thumbnails." under the "PrusaSlicer Thumbnails" options.

After that, magic!

<img src="https://user-images.githubusercontent.com/13375512/80015031-00ac5700-8486-11ea-8163-b959398c94b7.png" width="50%">

**Comment by flc85** [comment]
Thanks for all
