### ISSUE TITLE
Not working on network share

### ISSUE THREAD

**Issue by Conry70** [jneilliii/OctoPrint-PrusaSlicerThumbnails#64]
Hello,
I made a network share on my NAS in order that all the printers I have can refer to the same folders. Unfortunately if I browse the share the plugin is not working.
The mount is into 

/home/pi/.octoprint/uploads/nas

and the share is mounted in nfs. I tried to see if the permissions were right using putty and "pi" user and everything looks fine.
It would be nice if you can fix this.
Many thanks.

**Comment by jneilliii** [comment]
The problem is that the thumbnails are extracted into the plugin's data folder on the instance of OctoPrint that the file is uploaded to. If the file is never uploaded there is no way for me to know of their existence outside of initialing a crawl, from every printer instance that you are accessing the share from, which you can do from the plugin's settings. When you do that does the thumbnails come in then?
